"""empty message

ID de revision: 0ceb3936b082
Revisa: n4o5p6q7r8
Fecha de creacion: 2026-01-31 02:33:52.441297

"""
from typing import Sequence, Union

from alembic import op, context
import sqlalchemy as sa
import sqlmodel

# identificadores de revision, usados por Alembic.
revision: str = '0ceb3936b082'
down_revision: Union[str, Sequence[str], None] = 'n4o5p6q7r8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    if context.is_offline_mode():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def _has_table(name: str) -> bool:
        return inspector.has_table(name)

    def _has_column(table: str, column: str) -> bool:
        return any(col["name"] == column for col in inspector.get_columns(table))

    def _has_index(table: str, name: str) -> bool:
        return any(idx["name"] == name for idx in inspector.get_indexes(table))

    def _has_unique(table: str, name: str) -> bool:
        return any(uc["name"] == name for uc in inspector.get_unique_constraints(table))

    def _has_fk(table: str, columns: list[str], referred_table: str) -> bool:
        for fk in inspector.get_foreign_keys(table):
            if fk.get("referred_table") != referred_table:
                continue
            if fk.get("constrained_columns") == columns:
                return True
        return False

    if not _has_table("userbranch"):
        op.create_table(
            "userbranch",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("branch_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(["branch_id"], ["branch.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
            sa.PrimaryKeyConstraint("user_id", "branch_id"),
            sa.UniqueConstraint("user_id", "branch_id", name="uq_user_branch"),
        )

    with op.batch_alter_table("cashboxlog", schema=None) as batch_op:
        if not _has_column("cashboxlog", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("cashboxlog", "ix_cashboxlog_branch_id"):
            batch_op.create_index("ix_cashboxlog_branch_id", ["branch_id"], unique=False)
        if not _has_fk("cashboxlog", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("cashboxsession", schema=None) as batch_op:
        if not _has_column("cashboxsession", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("cashboxsession", "ix_cashboxsession_branch_id"):
            batch_op.create_index("ix_cashboxsession_branch_id", ["branch_id"], unique=False)
        if not _has_fk("cashboxsession", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("category", schema=None) as batch_op:
        if not _has_column("category", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("category", "ix_category_branch_id"):
            batch_op.create_index("ix_category_branch_id", ["branch_id"], unique=False)
        if not _has_unique("category", "uq_category_company_branch_name"):
            batch_op.create_unique_constraint(
                "uq_category_company_branch_name", ["company_id", "branch_id", "name"]
            )
        if not _has_fk("category", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("client", schema=None) as batch_op:
        if not _has_column("client", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("client", "ix_client_branch_id"):
            batch_op.create_index("ix_client_branch_id", ["branch_id"], unique=False)
        if not _has_unique("client", "uq_client_company_branch_dni"):
            batch_op.create_unique_constraint(
                "uq_client_company_branch_dni", ["company_id", "branch_id", "dni"]
            )
        if not _has_fk("client", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("companysettings", schema=None) as batch_op:
        if not _has_column("companysettings", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("companysettings", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("companysettings", "ix_companysettings_branch_id"):
            batch_op.create_index("ix_companysettings_branch_id", ["branch_id"], unique=False)
        if not _has_index("companysettings", "ix_companysettings_company_id"):
            batch_op.create_index("ix_companysettings_company_id", ["company_id"], unique=False)
        if not _has_unique("companysettings", "uq_companysettings_company_branch"):
            batch_op.create_unique_constraint(
                "uq_companysettings_company_branch", ["company_id", "branch_id"]
            )
        if not _has_fk("companysettings", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])
        if not _has_fk("companysettings", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])

    with op.batch_alter_table("fieldprice", schema=None) as batch_op:
        if not _has_column("fieldprice", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("fieldprice", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("fieldprice", "ix_fieldprice_branch_id"):
            batch_op.create_index("ix_fieldprice_branch_id", ["branch_id"], unique=False)
        if not _has_index("fieldprice", "ix_fieldprice_company_id"):
            batch_op.create_index("ix_fieldprice_company_id", ["company_id"], unique=False)
        if not _has_fk("fieldprice", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("fieldprice", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("fieldreservation", schema=None) as batch_op:
        if not _has_column("fieldreservation", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("fieldreservation", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("fieldreservation", "ix_fieldreservation_branch_id"):
            batch_op.create_index("ix_fieldreservation_branch_id", ["branch_id"], unique=False)
        if not _has_index("fieldreservation", "ix_fieldreservation_company_id"):
            batch_op.create_index("ix_fieldreservation_company_id", ["company_id"], unique=False)
        if not _has_fk("fieldreservation", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])
        if not _has_fk("fieldreservation", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])

    with op.batch_alter_table("paymentmethod", schema=None) as batch_op:
        if not _has_column("paymentmethod", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("paymentmethod", "ix_paymentmethod_branch_id"):
            batch_op.create_index("ix_paymentmethod_branch_id", ["branch_id"], unique=False)
        if not _has_unique("paymentmethod", "uq_paymentmethod_company_branch_code"):
            batch_op.create_unique_constraint(
                "uq_paymentmethod_company_branch_code",
                ["company_id", "branch_id", "code"],
            )
        if not _has_unique("paymentmethod", "uq_paymentmethod_company_branch_method_id"):
            batch_op.create_unique_constraint(
                "uq_paymentmethod_company_branch_method_id",
                ["company_id", "branch_id", "method_id"],
            )
        if not _has_fk("paymentmethod", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("product", schema=None) as batch_op:
        if not _has_column("product", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("product", "ix_product_branch_id"):
            batch_op.create_index("ix_product_branch_id", ["branch_id"], unique=False)
        if not _has_unique("product", "uq_product_company_branch_barcode"):
            batch_op.create_unique_constraint(
                "uq_product_company_branch_barcode", ["company_id", "branch_id", "barcode"]
            )
        if not _has_fk("product", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("purchase", schema=None) as batch_op:
        if not _has_column("purchase", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("purchase", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("purchase", "ix_purchase_branch_id"):
            batch_op.create_index("ix_purchase_branch_id", ["branch_id"], unique=False)
        if not _has_index("purchase", "ix_purchase_company_id"):
            batch_op.create_index("ix_purchase_company_id", ["company_id"], unique=False)
        if not _has_unique("purchase", "uq_purchase_company_branch_supplier_doc"):
            batch_op.create_unique_constraint(
                "uq_purchase_company_branch_supplier_doc",
                ["company_id", "branch_id", "supplier_id", "doc_type", "series", "number"],
            )
        if not _has_fk("purchase", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("purchase", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("purchaseitem", schema=None) as batch_op:
        if not _has_column("purchaseitem", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("purchaseitem", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("purchaseitem", "ix_purchaseitem_branch_id"):
            batch_op.create_index("ix_purchaseitem_branch_id", ["branch_id"], unique=False)
        if not _has_index("purchaseitem", "ix_purchaseitem_company_id"):
            batch_op.create_index("ix_purchaseitem_company_id", ["company_id"], unique=False)
        if not _has_fk("purchaseitem", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("purchaseitem", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("sale", schema=None) as batch_op:
        if not _has_column("sale", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("sale", "ix_sale_branch_id"):
            batch_op.create_index("ix_sale_branch_id", ["branch_id"], unique=False)
        if not _has_fk("sale", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("saleinstallment", schema=None) as batch_op:
        if not _has_column("saleinstallment", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("saleinstallment", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("saleinstallment", "ix_saleinstallment_branch_id"):
            batch_op.create_index("ix_saleinstallment_branch_id", ["branch_id"], unique=False)
        if not _has_index("saleinstallment", "ix_saleinstallment_company_id"):
            batch_op.create_index("ix_saleinstallment_company_id", ["company_id"], unique=False)
        if not _has_fk("saleinstallment", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("saleinstallment", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("saleitem", schema=None) as batch_op:
        if not _has_column("saleitem", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("saleitem", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("saleitem", "ix_saleitem_branch_id"):
            batch_op.create_index("ix_saleitem_branch_id", ["branch_id"], unique=False)
        if not _has_index("saleitem", "ix_saleitem_company_id"):
            batch_op.create_index("ix_saleitem_company_id", ["company_id"], unique=False)
        if not _has_fk("saleitem", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("saleitem", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("salepayment", schema=None) as batch_op:
        if not _has_column("salepayment", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("salepayment", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("salepayment", "ix_salepayment_branch_id"):
            batch_op.create_index("ix_salepayment_branch_id", ["branch_id"], unique=False)
        if not _has_index("salepayment", "ix_salepayment_company_id"):
            batch_op.create_index("ix_salepayment_company_id", ["company_id"], unique=False)
        if not _has_fk("salepayment", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("salepayment", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("stockmovement", schema=None) as batch_op:
        if not _has_column("stockmovement", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("stockmovement", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("stockmovement", "ix_stockmovement_branch_id"):
            batch_op.create_index("ix_stockmovement_branch_id", ["branch_id"], unique=False)
        if not _has_index("stockmovement", "ix_stockmovement_company_id"):
            batch_op.create_index("ix_stockmovement_company_id", ["company_id"], unique=False)
        if not _has_fk("stockmovement", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])
        if not _has_fk("stockmovement", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    with op.batch_alter_table("supplier", schema=None) as batch_op:
        if not _has_column("supplier", "company_id"):
            batch_op.add_column(sa.Column("company_id", sa.Integer(), nullable=True))
        if not _has_column("supplier", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("supplier", "ix_supplier_tax_id"):
            batch_op.create_index("ix_supplier_tax_id", ["tax_id"], unique=False)
        if not _has_index("supplier", "ix_supplier_branch_id"):
            batch_op.create_index("ix_supplier_branch_id", ["branch_id"], unique=False)
        if not _has_index("supplier", "ix_supplier_company_id"):
            batch_op.create_index("ix_supplier_company_id", ["company_id"], unique=False)
        if not _has_unique("supplier", "uq_supplier_company_branch_tax_id"):
            batch_op.create_unique_constraint(
                "uq_supplier_company_branch_tax_id",
                ["company_id", "branch_id", "tax_id"],
            )
        if not _has_fk("supplier", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])
        if not _has_fk("supplier", ["company_id"], "company"):
            batch_op.create_foreign_key(None, "company", ["company_id"], ["id"])

    with op.batch_alter_table("unit", schema=None) as batch_op:
        if not _has_column("unit", "branch_id"):
            batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        if not _has_index("unit", "ix_unit_branch_id"):
            batch_op.create_index("ix_unit_branch_id", ["branch_id"], unique=False)
        if not _has_unique("unit", "uq_unit_company_branch_name"):
            batch_op.create_unique_constraint(
                "uq_unit_company_branch_name", ["company_id", "branch_id", "name"]
            )
        if not _has_fk("unit", ["branch_id"], "branch"):
            batch_op.create_foreign_key(None, "branch", ["branch_id"], ["id"])

    bind.execute(
        sa.text(
            "INSERT INTO branch (company_id, name, address) "
            "SELECT c.id, 'Casa Matriz', '' "
            "FROM company c "
            "LEFT JOIN branch b ON b.company_id = c.id "
            "WHERE b.id IS NULL"
        )
    )

    bind.execute(
        sa.text(
            "UPDATE companysettings SET company_id = 1 WHERE company_id IS NULL"
        )
    )
    bind.execute(
        sa.text("UPDATE fieldprice SET company_id = 1 WHERE company_id IS NULL")
    )
    bind.execute(
        sa.text(
            "UPDATE fieldreservation fr "
            "LEFT JOIN user u ON u.id = fr.user_id "
            "SET fr.company_id = COALESCE(fr.company_id, u.company_id, 1) "
            "WHERE fr.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE purchase p "
            "LEFT JOIN user u ON u.id = p.user_id "
            "SET p.company_id = COALESCE(p.company_id, u.company_id, 1) "
            "WHERE p.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE supplier s "
            "JOIN (SELECT supplier_id, MIN(company_id) AS company_id "
            "FROM purchase GROUP BY supplier_id) p "
            "ON p.supplier_id = s.id "
            "SET s.company_id = p.company_id "
            "WHERE s.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text("UPDATE supplier SET company_id = 1 WHERE company_id IS NULL")
    )
    bind.execute(
        sa.text(
            "UPDATE saleitem si "
            "JOIN sale s ON s.id = si.sale_id "
            "SET si.company_id = s.company_id "
            "WHERE si.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE salepayment sp "
            "JOIN sale s ON s.id = sp.sale_id "
            "SET sp.company_id = s.company_id "
            "WHERE sp.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE saleinstallment si "
            "JOIN sale s ON s.id = si.sale_id "
            "SET si.company_id = s.company_id "
            "WHERE si.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE purchaseitem pi "
            "JOIN purchase p ON p.id = pi.purchase_id "
            "SET pi.company_id = p.company_id "
            "WHERE pi.company_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE stockmovement sm "
            "LEFT JOIN product p ON p.id = sm.product_id "
            "LEFT JOIN user u ON u.id = sm.user_id "
            "SET sm.company_id = COALESCE(sm.company_id, p.company_id, u.company_id, 1) "
            "WHERE sm.company_id IS NULL"
        )
    )

    bind.execute(
        sa.text(
            "UPDATE saleitem si "
            "JOIN sale s ON s.id = si.sale_id "
            "SET si.branch_id = s.branch_id "
            "WHERE si.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE salepayment sp "
            "JOIN sale s ON s.id = sp.sale_id "
            "SET sp.branch_id = s.branch_id "
            "WHERE sp.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE saleinstallment si "
            "JOIN sale s ON s.id = si.sale_id "
            "SET si.branch_id = s.branch_id "
            "WHERE si.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE purchase p "
            "LEFT JOIN user u ON u.id = p.user_id "
            "SET p.branch_id = COALESCE(p.branch_id, u.branch_id) "
            "WHERE p.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE purchaseitem pi "
            "JOIN purchase p ON p.id = pi.purchase_id "
            "SET pi.branch_id = p.branch_id "
            "WHERE pi.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE fieldreservation fr "
            "LEFT JOIN user u ON u.id = fr.user_id "
            "SET fr.branch_id = COALESCE(fr.branch_id, u.branch_id) "
            "WHERE fr.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE cashboxlog cl "
            "LEFT JOIN user u ON u.id = cl.user_id "
            "SET cl.branch_id = COALESCE(cl.branch_id, u.branch_id) "
            "WHERE cl.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE cashboxsession cs "
            "LEFT JOIN user u ON u.id = cs.user_id "
            "SET cs.branch_id = COALESCE(cs.branch_id, u.branch_id) "
            "WHERE cs.branch_id IS NULL"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE stockmovement sm "
            "LEFT JOIN product p ON p.id = sm.product_id "
            "LEFT JOIN user u ON u.id = sm.user_id "
            "SET sm.branch_id = COALESCE(sm.branch_id, p.branch_id, u.branch_id) "
            "WHERE sm.branch_id IS NULL"
        )
    )

    default_branch = (
        "SELECT company_id, MIN(id) AS branch_id FROM branch GROUP BY company_id"
    )
    for table in [
        "cashboxlog",
        "cashboxsession",
        "category",
        "client",
        "companysettings",
        "fieldprice",
        "fieldreservation",
        "paymentmethod",
        "product",
        "purchase",
        "purchaseitem",
        "sale",
        "saleinstallment",
        "saleitem",
        "salepayment",
        "stockmovement",
        "supplier",
        "unit",
    ]:
        bind.execute(
            sa.text(
                f"UPDATE {table} t "
                f"JOIN ({default_branch}) b ON b.company_id = t.company_id "
                "SET t.branch_id = b.branch_id "
                "WHERE t.branch_id IS NULL"
            )
        )

    with op.batch_alter_table("cashboxlog", schema=None) as batch_op:
        if _has_column("cashboxlog", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("cashboxsession", schema=None) as batch_op:
        if _has_column("cashboxsession", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("category", schema=None) as batch_op:
        if _has_column("category", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("client", schema=None) as batch_op:
        if _has_column("client", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("companysettings", schema=None) as batch_op:
        if _has_column("companysettings", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("companysettings", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("fieldprice", schema=None) as batch_op:
        if _has_column("fieldprice", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("fieldprice", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("fieldreservation", schema=None) as batch_op:
        if _has_column("fieldreservation", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("fieldreservation", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("paymentmethod", schema=None) as batch_op:
        if _has_column("paymentmethod", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("product", schema=None) as batch_op:
        if _has_column("product", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("purchase", schema=None) as batch_op:
        if _has_column("purchase", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("purchase", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("purchaseitem", schema=None) as batch_op:
        if _has_column("purchaseitem", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("purchaseitem", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("sale", schema=None) as batch_op:
        if _has_column("sale", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("saleinstallment", schema=None) as batch_op:
        if _has_column("saleinstallment", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("saleinstallment", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("saleitem", schema=None) as batch_op:
        if _has_column("saleitem", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("saleitem", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("salepayment", schema=None) as batch_op:
        if _has_column("salepayment", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("salepayment", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("stockmovement", schema=None) as batch_op:
        if _has_column("stockmovement", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("stockmovement", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("supplier", schema=None) as batch_op:
        if _has_column("supplier", "company_id"):
            batch_op.alter_column("company_id", existing_type=sa.Integer(), nullable=False)
        if _has_column("supplier", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table("unit", schema=None) as batch_op:
        if _has_column("unit", "branch_id"):
            batch_op.alter_column("branch_id", existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    if context.is_offline_mode():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_unit_company_branch_name', type_='unique')
        batch_op.create_index(batch_op.f('uq_unit_company_name'), ['company_id', 'name'], unique=True)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_supplier_company_branch_tax_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_supplier_tax_id'), ['tax_id'], unique=True)
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('salepayment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_saleinstallment_sale_status'), ['sale_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_saleinstallment_duedate_status'), ['due_date', 'status'], unique=False)
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('purchaseitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_purchaseitem_product_id'), ['product_id'], unique=False)
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_purchase_company_branch_supplier_doc', type_='unique')
        batch_op.create_index(batch_op.f('uq_purchase_supplier_doc'), ['supplier_id', 'doc_type', 'series', 'number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_issue_date'), ['issue_date'], unique=False)
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_product_company_branch_barcode', type_='unique')
        batch_op.create_index(batch_op.f('uq_product_company_barcode'), ['company_id', 'barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_search'), ['category', 'description'], unique=False)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_paymentmethod_company_branch_method_id', type_='unique')
        batch_op.drop_constraint('uq_paymentmethod_company_branch_code', type_='unique')
        batch_op.create_index(batch_op.f('uq_paymentmethod_company_method_id'), ['company_id', 'method_id'], unique=True)
        batch_op.create_index(batch_op.f('uq_paymentmethod_company_code'), ['company_id', 'code'], unique=True)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('companysettings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_companysettings_company_branch', type_='unique')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_client_company_branch_dni', type_='unique')
        batch_op.create_index(batch_op.f('uq_client_company_dni'), ['company_id', 'dni'], unique=True)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_category_company_branch_name', type_='unique')
        batch_op.create_index(batch_op.f('uq_category_company_name'), ['company_id', 'name'], unique=True)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_cashboxlog_timestamp_action'), ['timestamp', 'action'], unique=False)
        batch_op.drop_column('branch_id')

    op.drop_table('userbranch')
    # ### end Alembic commands ###
