"""multi-vertical-gaps-batch-attributes-stock-threshold

ID de revision: 1714b338ecb6
Revisa: l6m7n8o9p0q1
Fecha de creacion: 2026-04-04 06:35:34.743697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# identificadores de revision, usados por Alembic.
revision: str = '1714b338ecb6'
down_revision: Union[str, Sequence[str], None] = 'l6m7n8o9p0q1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companybillingconfig', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('document_lookup_cache', schema=None) as batch_op:
        batch_op.alter_column('raw_json',
               nullable=True)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fieldreservation_end_datetime'), ['end_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_fieldreservation_status'), ['status'], unique=False)
        batch_op.create_index('ix_fieldreservation_tenant_status', ['company_id', 'branch_id', 'status'], unique=False)

    with op.batch_alter_table('fiscaldocument', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('taxable_amount',
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('tax_amount',
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('total_amount',
               nullable=True,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('ix_product_tenant_barcode', ['company_id', 'branch_id', 'barcode'], unique=False)
        batch_op.create_index('ix_product_tenant_category', ['company_id', 'branch_id', 'category'], unique=False)

    with op.batch_alter_table('productbatch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productbatch_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_productbatch_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productbatch_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_index('ix_productbatch_tenant_product', ['company_id', 'branch_id', 'product_id'], unique=False)
        batch_op.create_index('ix_productbatch_tenant_variant', ['company_id', 'branch_id', 'product_variant_id'], unique=False)

    with op.batch_alter_table('productvariant', schema=None) as batch_op:
        batch_op.create_index('ix_productvariant_tenant_product', ['company_id', 'branch_id', 'product_id'], unique=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_tenant_date', ['company_id', 'branch_id', 'issue_date'], unique=False)
        batch_op.create_index('ix_purchase_tenant_supplier', ['company_id', 'branch_id', 'supplier_id'], unique=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_receipt_type'))
        batch_op.create_index(batch_op.f('ix_sale_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.create_index('ix_saleinstallment_tenant_status', ['company_id', 'branch_id', 'status'], unique=False)

    with op.batch_alter_table('salepayment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salepayment_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index('ix_salepayment_tenant_sale', ['company_id', 'branch_id', 'sale_id'], unique=False)

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stockmovement_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_stockmovement_tenant_product', ['company_id', 'branch_id', 'product_id'], unique=False)
        batch_op.create_index('ix_stockmovement_tenant_timestamp', ['company_id', 'branch_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_stockmovement_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_stockmovement_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stockmovement_type'))
        batch_op.drop_index(batch_op.f('ix_stockmovement_timestamp'))
        batch_op.drop_index('ix_stockmovement_tenant_timestamp')
        batch_op.drop_index('ix_stockmovement_tenant_product')
        batch_op.drop_index(batch_op.f('ix_stockmovement_product_id'))

    with op.batch_alter_table('salepayment', schema=None) as batch_op:
        batch_op.drop_index('ix_salepayment_tenant_sale')
        batch_op.drop_index(batch_op.f('ix_salepayment_sale_id'))

    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.drop_index('ix_saleinstallment_tenant_status')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_user_id'))
        batch_op.drop_index(batch_op.f('ix_sale_status'))
        batch_op.create_index(batch_op.f('ix_sale_receipt_type'), ['receipt_type'], unique=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_tenant_supplier')
        batch_op.drop_index('ix_purchase_tenant_date')

    with op.batch_alter_table('productvariant', schema=None) as batch_op:
        batch_op.drop_index('ix_productvariant_tenant_product')

    with op.batch_alter_table('productbatch', schema=None) as batch_op:
        batch_op.drop_index('ix_productbatch_tenant_variant')
        batch_op.drop_index('ix_productbatch_tenant_product')
        batch_op.drop_index(batch_op.f('ix_productbatch_product_variant_id'))
        batch_op.drop_index(batch_op.f('ix_productbatch_product_id'))
        batch_op.drop_index(batch_op.f('ix_productbatch_expiration_date'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('ix_product_tenant_category')
        batch_op.drop_index('ix_product_tenant_barcode')

    with op.batch_alter_table('fiscaldocument', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('tax_amount',
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('taxable_amount',
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.drop_index('ix_fieldreservation_tenant_status')
        batch_op.drop_index(batch_op.f('ix_fieldreservation_status'))
        batch_op.drop_index(batch_op.f('ix_fieldreservation_end_datetime'))

    with op.batch_alter_table('document_lookup_cache', schema=None) as batch_op:
        batch_op.alter_column('raw_json',
               nullable=False)

    with op.batch_alter_table('companybillingconfig', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###
