"""add_reservation_fields

Revision ID: 1808e5b7a4c2
Revises: cce22488e742
Create Date: 2025-12-05 01:36:58.239591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1808e5b7a4c2'
down_revision: Union[str, Sequence[str], None] = 'cce22488e742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('delete_reason')
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
