"""decimal_fields

Revision ID: 23c0e16c9726
Revises: 9ab675eb20c0
Create Date: 2025-12-29 02:25:15.234823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '23c0e16c9726'
down_revision: Union[str, Sequence[str], None] = '9ab675eb20c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.alter_column('opening_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('closing_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('paid_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('sale_price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.alter_column('paid_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.alter_column('closing_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('opening_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
