"""empty message

ID de revision: 3f8344b116db
Revisa: b66fcf4607d8
Fecha de creacion: 2026-01-31 12:32:00.194726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# identificadores de revision, usados por Alembic.
revision: str = '3f8344b116db'
down_revision: Union[str, Sequence[str], None] = 'b66fcf4607d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbranch', schema=None) as batch_op:
        batch_op.drop_constraint('PRIMARY', type_='primary')
        batch_op.add_column(
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.create_primary_key('pk_userbranch', ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbranch', schema=None) as batch_op:
        batch_op.drop_constraint('pk_userbranch', type_='primary')
        batch_op.drop_column('id')
        batch_op.create_primary_key('PRIMARY', ['user_id', 'branch_id'])

    # ### end Alembic commands ###
