"""empty message

ID de revision: 41f4cbde7e0e
Revisa: h1i2j3k4l5
Fecha de creacion: 2026-02-07 11:52:46.416221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revision, usados por Alembic.
revision: str = '41f4cbde7e0e'
down_revision: Union[str, Sequence[str], None] = 'h1i2j3k4l5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashboxlog_company_branch_timestamp'))

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fieldreservation_company_branch_sport_start'))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_company_branch_timestamp'))

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saleitem_company_branch_product'))
        batch_op.drop_index(batch_op.f('ix_saleitem_company_branch_sale'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saleitem_company_branch_sale'), ['company_id', 'branch_id', 'sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saleitem_company_branch_product'), ['company_id', 'branch_id', 'product_id'], unique=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_company_branch_timestamp'), ['company_id', 'branch_id', 'timestamp'], unique=False)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fieldreservation_company_branch_sport_start'), ['company_id', 'branch_id', 'sport', 'start_datetime'], unique=False)

    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashboxlog_company_branch_timestamp'), ['company_id', 'branch_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###
