"""Actualizacion masiva produccion

Revision ID: 4375e70a546e
Revises: c41b78cb00e8
Create Date: 2026-01-13 10:30:50.496225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4375e70a546e'
down_revision: Union[str, Sequence[str], None] = 'c41b78cb00e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
