"""add cashboxlog payment_method

Revision ID: 4946658237b1
Revises: d92e5d8cb880
Create Date: 2026-01-03 21:46:31.308187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4946658237b1'
down_revision: Union[str, Sequence[str], None] = 'd92e5d8cb880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashboxlog', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_cashboxlog_payment_method'), 'cashboxlog', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cashboxlog_payment_method'), table_name='cashboxlog')
    op.drop_column('cashboxlog', 'payment_method')
    # ### end Alembic commands ###
