"""empty message

ID de revision: 520be8374697
Revisa: f5a6b7c8d9e0
Fecha de creacion: 2026-03-05 18:50:17.002109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# identificadores de revision, usados por Alembic.
revision: str = '520be8374697'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """Verifica si un índice existe antes de intentar eliminarlo."""
    bind = op.get_bind()
    insp = inspect(bind)
    return any(ix["name"] == index_name for ix in insp.get_indexes(table_name))


def upgrade() -> None:
    """Actualizar esquema. existing_type requerido por MySQL en MODIFY COLUMN."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)
        if _index_exists('cashboxlog', 'ix_cashboxlog_timestamp_action'):
            batch_op.drop_index(batch_op.f('ix_cashboxlog_timestamp_action'))

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('companysettings', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)
        if _index_exists('product', 'ix_product_search'):
            batch_op.drop_index(batch_op.f('ix_product_search'))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)
        if _index_exists('purchase', 'ix_purchase_issue_date'):
            batch_op.drop_index(batch_op.f('ix_purchase_issue_date'))

    with op.batch_alter_table('purchaseitem', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)
        if _index_exists('saleinstallment', 'ix_saleinstallment_duedate_status'):
            batch_op.drop_index(batch_op.f('ix_saleinstallment_duedate_status'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema. existing_type requerido por MySQL."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saleinstallment_duedate_status'), ['due_date', 'status'], unique=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('purchaseitem', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_issue_date'), ['issue_date'], unique=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_search'), ['category', 'description'], unique=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('companysettings', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashboxlog_timestamp_action'), ['timestamp', 'action'], unique=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###
