"""empty message

ID de revision: 520be8374697
Revisa: f5a6b7c8d9e0
Fecha de creacion: 2026-03-05 18:50:17.002109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revision, usados por Alembic.
revision: str = '520be8374697'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema. existing_type requerido por MySQL en MODIFY COLUMN."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('companysettings', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('purchaseitem', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema. existing_type requerido por MySQL."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saleinstallment', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('purchaseitem', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('fieldreservation', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('fieldprice', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('companysettings', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('cashboxsession', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###
