"""add_cashbox_arqueo_and_sale_returns

ID de revision: 5cb0f4e0b921
Revisa: q8r9s0t1u2v3
Fecha de creacion: 2026-04-13 08:03:31.816093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# identificadores de revision, usados por Alembic.
revision: str = '5cb0f4e0b921'
down_revision: Union[str, Sequence[str], None] = 'q8r9s0t1u2v3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salereturn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('original_sale_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salereturn_branch_id'), 'salereturn', ['branch_id'], unique=False)
    op.create_index(op.f('ix_salereturn_company_id'), 'salereturn', ['company_id'], unique=False)
    op.create_index(op.f('ix_salereturn_original_sale_id'), 'salereturn', ['original_sale_id'], unique=False)
    op.create_index('ix_salereturn_tenant_sale', 'salereturn', ['company_id', 'branch_id', 'original_sale_id'], unique=False)
    op.create_table('salereturnitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('refund_subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('product_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_batch_id'], ['productbatch.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['productvariant.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['saleitem.id'], ),
    sa.ForeignKeyConstraint(['sale_return_id'], ['salereturn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salereturnitem_sale_return_id'), 'salereturnitem', ['sale_return_id'], unique=False)
    op.add_column('cashboxsession', sa.Column('counted_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('cashboxsession', sa.Column('denomination_detail', sa.Text(), nullable=True))
    op.alter_column('sale', 'receipt_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'receipt_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('cashboxsession', 'denomination_detail')
    op.drop_column('cashboxsession', 'counted_amount')
    op.drop_index(op.f('ix_salereturnitem_sale_return_id'), table_name='salereturnitem')
    op.drop_table('salereturnitem')
    op.drop_index('ix_salereturn_tenant_sale', table_name='salereturn')
    op.drop_index(op.f('ix_salereturn_original_sale_id'), table_name='salereturn')
    op.drop_index(op.f('ix_salereturn_company_id'), table_name='salereturn')
    op.drop_index(op.f('ix_salereturn_branch_id'), table_name='salereturn')
    op.drop_table('salereturn')
    # ### end Alembic commands ###
