"""add_subscription_lifecycle

ID de revision: 7ec2b7d14481
Revisa: 72d06d1dd022
Fecha de creacion: 2026-02-01 00:57:30.129667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# identificadores de revision, usados por Alembic.
revision: str = '7ec2b7d14481'
down_revision: Union[str, Sequence[str], None] = '72d06d1dd022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "subscription_status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="active",
        ),
    )
    op.add_column(
        "company",
        sa.Column("subscription_ends_at", sa.DateTime(), nullable=True),
    )
    op.alter_column("company", "subscription_status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "subscription_ends_at")
    op.drop_column("company", "subscription_status")
    # ### end Alembic commands ###
