"""add_saas_plan_fields

ID de revision: 860d23acfa63
Revisa: c9f1a2b3c4d5
Fecha de creacion: 2026-01-31 21:15:49.473141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# identificadores de revision, usados por Alembic.
revision: str = '860d23acfa63'
down_revision: Union[str, Sequence[str], None] = 'c9f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "plan_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="trial",
        ),
    )
    op.add_column(
        "company",
        sa.Column(
            "max_branches",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )
    op.add_column(
        "company",
        sa.Column(
            "max_users",
            sa.Integer(),
            nullable=False,
            server_default="2",
        ),
    )
    op.add_column(
        "company",
        sa.Column(
            "has_reservations_module",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.add_column(
        "company",
        sa.Column(
            "has_electronic_billing",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("company", "plan_type", server_default=None)
    op.alter_column("company", "max_branches", server_default=None)
    op.alter_column("company", "max_users", server_default=None)
    op.alter_column("company", "has_reservations_module", server_default=None)
    op.alter_column("company", "has_electronic_billing", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "has_electronic_billing")
    op.drop_column("company", "has_reservations_module")
    op.drop_column("company", "max_users")
    op.drop_column("company", "max_branches")
    op.drop_column("company", "plan_type")
    # ### end Alembic commands ###
