"""add_cashbox_log_details

Revision ID: 9ab675eb20c0
Revises: 1808e5b7a4c2
Create Date: 2025-12-11 03:20:31.531833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9ab675eb20c0'
down_revision: Union[str, Sequence[str], None] = '1808e5b7a4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               nullable=False,
               existing_server_default=sa.text("'Unidad'"))
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashboxlog', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               nullable=True,
               existing_server_default=sa.text("'Unidad'"))
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
