"""empty message

ID de revision: b66fcf4607d8
Revisa: baecfbbf817e
Fecha de creacion: 2026-01-31 03:05:03.545148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revision, usados por Alembic.
revision: str = 'b66fcf4607d8'
down_revision: Union[str, Sequence[str], None] = 'baecfbbf817e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_tax_id'))
        batch_op.create_index(batch_op.f('ix_supplier_tax_id'), ['tax_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_tax_id'))
        batch_op.create_index(batch_op.f('ix_supplier_tax_id'), ['tax_id'], unique=True)

    # ### end Alembic commands ###
