"""empty message

ID de revision: baecfbbf817e
Revisa: 0ceb3936b082
Fecha de creacion: 2026-01-31 03:01:06.804648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# identificadores de revision, usados por Alembic.
revision: str = 'baecfbbf817e'
down_revision: Union[str, Sequence[str], None] = '0ceb3936b082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('salepayment', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('uq_unit_company_name'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_unit_company_name'), ['company_id', 'name'], unique=True)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('salepayment', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)



    # ### end Alembic commands ###
