"""empty message

ID de revision: baecfbbf817e
Revisa: 0ceb3936b082
Fecha de creacion: 2026-01-31 03:01:06.804648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect as sa_inspect

# identificadores de revision, usados por Alembic.
revision: str = 'baecfbbf817e'
down_revision: Union[str, Sequence[str], None] = '0ceb3936b082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema de forma idempotente y compatible con MySQL."""
    bind = op.get_bind()
    inspector = sa_inspect(bind)

    def _refresh() -> None:
        nonlocal inspector
        inspector = sa_inspect(bind)

    def _has_table(table_name: str) -> bool:
        return inspector.has_table(table_name)

    def _has_index(table_name: str, index_name: str) -> bool:
        return any(idx["name"] == index_name for idx in inspector.get_indexes(table_name))

    def _column_nullable(table_name: str, column_name: str) -> bool | None:
        for column in inspector.get_columns(table_name):
            if column["name"] == column_name:
                return bool(column.get("nullable", True))
        return None

    def _has_fk(table_name: str, constrained_cols: list[str], referred_table: str) -> bool:
        for fk in inspector.get_foreign_keys(table_name):
            if fk.get("referred_table") != referred_table:
                continue
            if fk.get("constrained_columns") == constrained_cols:
                return True
        return False

    def _drop_fk(table_name: str, constrained_col: str, referred_table: str) -> list[tuple[str | None, str, str]]:
        dropped: list[tuple[str | None, str, str]] = []
        for fk in inspector.get_foreign_keys(table_name):
            if fk.get("referred_table") != referred_table:
                continue
            if fk.get("constrained_columns") != [constrained_col]:
                continue
            fk_name = fk.get("name")
            if fk_name:
                op.drop_constraint(fk_name, table_name, type_="foreignkey")
                dropped.append((fk_name, constrained_col, referred_table))
        if dropped:
            _refresh()
        return dropped

    def _ensure_fk(table_name: str, fk_name: str | None, constrained_col: str, referred_table: str) -> None:
        if not _has_fk(table_name, [constrained_col], referred_table):
            op.create_foreign_key(
                fk_name or f"fk_{table_name}_{constrained_col}",
                table_name,
                referred_table,
                [constrained_col],
                ["id"],
            )
            _refresh()

    def _enforce_not_null_with_fk(table_name: str) -> None:
        if not _has_table(table_name):
            return

        dropped_fks: list[tuple[str | None, str, str]] = []
        if _column_nullable(table_name, "company_id") is True:
            dropped_fks.extend(_drop_fk(table_name, "company_id", "company"))
            op.alter_column(
                table_name,
                "company_id",
                existing_type=mysql.INTEGER(),
                nullable=False,
            )
            _refresh()

        if _column_nullable(table_name, "branch_id") is True:
            dropped_fks.extend(_drop_fk(table_name, "branch_id", "branch"))
            op.alter_column(
                table_name,
                "branch_id",
                existing_type=mysql.INTEGER(),
                nullable=False,
            )
            _refresh()

        for fk_name, constrained_col, referred_table in dropped_fks:
            _ensure_fk(table_name, fk_name, constrained_col, referred_table)

    for table_name in ("saleitem", "salepayment", "stockmovement", "supplier"):
        _enforce_not_null_with_fk(table_name)

    if _has_table("unit"):
        dropped_unit_fk = []
        if _column_nullable("unit", "branch_id") is True:
            dropped_unit_fk = _drop_fk("unit", "branch_id", "branch")
            op.alter_column(
                "unit",
                "branch_id",
                existing_type=mysql.INTEGER(),
                nullable=False,
            )
            _refresh()
        for fk_name, constrained_col, referred_table in dropped_unit_fk:
            _ensure_fk("unit", fk_name, constrained_col, referred_table)

        legacy_index = op.f("uq_unit_company_name")
        if _has_index("unit", legacy_index):
            op.drop_index(legacy_index, table_name="unit")


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_unit_company_name'), ['company_id', 'name'], unique=True)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stockmovement', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('salepayment', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('saleitem', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)



    # ### end Alembic commands ###
