"""add_performance_indexes_fixed

Revision ID: c41b78cb00e8
Revises: e6a2d1cf185c
Create Date: 2026-01-04 08:15:25.971435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41b78cb00e8'
down_revision: Union[str, Sequence[str], None] = 'e6a2d1cf185c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cashboxlog_action'), 'cashboxlog', ['action'], unique=False)
    op.create_index(op.f('ix_cashboxlog_payment_method_id'), 'cashboxlog', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_cashboxlog_timestamp'), 'cashboxlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_product_description'), 'product', ['description'], unique=False)
    op.create_index(op.f('ix_sale_client_id'), 'sale', ['client_id'], unique=False)
    op.create_index(op.f('ix_sale_timestamp'), 'sale', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_timestamp'), table_name='sale')
    op.drop_index(op.f('ix_sale_client_id'), table_name='sale')
    op.drop_index(op.f('ix_product_description'), table_name='product')
    op.drop_index(op.f('ix_cashboxlog_timestamp'), table_name='cashboxlog')
    op.drop_index(op.f('ix_cashboxlog_payment_method_id'), table_name='cashboxlog')
    op.drop_index(op.f('ix_cashboxlog_action'), table_name='cashboxlog')
    # ### end Alembic commands ###
