"""add config tables

Revision ID: cce22488e742
Revises: fed7e3693860
Create Date: 2025-12-04 23:51:03.346984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cce22488e742'
down_revision: Union[str, Sequence[str], None] = 'fed7e3693860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_code'), ['code'], unique=True)

    op.create_table('fieldprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paymentmethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paymentmethod_method_id'), ['method_id'], unique=True)

    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allows_decimal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_name'))

    op.drop_table('unit')
    with op.batch_alter_table('paymentmethod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paymentmethod_method_id'))

    op.drop_table('paymentmethod')
    op.drop_table('fieldprice')
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_code'))

    op.drop_table('currency')
    # ### end Alembic commands ###
