"""add_missing_composite_indexes

ID de revision: cfa77546ed70
Revisa: 520be8374697
Fecha de creacion: 2026-03-05 18:03:49.039068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revision, usados por Alembic.
revision: str = 'cfa77546ed70'
down_revision: Union[str, Sequence[str], None] = '520be8374697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(conn, index_name: str, table_name: str) -> bool:
    """Verifica si un indice ya existe en la tabla (MySQL)."""
    result = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM information_schema.statistics "
            "WHERE table_schema = DATABASE() "
            "AND table_name = :table AND index_name = :idx"
        ),
        {"table": table_name, "idx": index_name},
    )
    return result.scalar() > 0


def upgrade() -> None:
    """Actualizar esquema."""
    conn = op.get_bind()
    indexes = [
        ('ix_cashboxlog_timestamp_action', 'cashboxlog', ['timestamp', 'action']),
        ('ix_product_search', 'product', ['category', 'description']),
        ('ix_purchase_issue_date', 'purchase', ['issue_date']),
        ('ix_saleinstallment_duedate_status', 'saleinstallment', ['due_date', 'status']),
    ]
    for idx_name, table, columns in indexes:
        if not _index_exists(conn, idx_name, table):
            op.create_index(idx_name, table, columns, unique=False)


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saleinstallment_duedate_status', table_name='saleinstallment')
    op.drop_index('ix_purchase_issue_date', table_name='purchase')
    op.drop_index('ix_product_search', table_name='product')
    op.drop_index('ix_cashboxlog_timestamp_action', table_name='cashboxlog')
    # ### end Alembic commands ###
