"""add_missing_composite_indexes

ID de revision: cfa77546ed70
Revisa: 520be8374697
Fecha de creacion: 2026-03-05 18:03:49.039068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revision, usados por Alembic.
revision: str = 'cfa77546ed70'
down_revision: Union[str, Sequence[str], None] = '520be8374697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actualizar esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cashboxlog_timestamp_action', 'cashboxlog', ['timestamp', 'action'], unique=False)
    op.create_index('ix_product_search', 'product', ['category', 'description'], unique=False)
    op.create_index('ix_purchase_issue_date', 'purchase', ['issue_date'], unique=False)
    op.create_index('ix_saleinstallment_duedate_status', 'saleinstallment', ['due_date', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revertir esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saleinstallment_duedate_status', table_name='saleinstallment')
    op.drop_index('ix_purchase_issue_date', table_name='purchase')
    op.drop_index('ix_product_search', table_name='product')
    op.drop_index('ix_cashboxlog_timestamp_action', table_name='cashboxlog')
    # ### end Alembic commands ###
