"""Refactor_RBAC_y_SalePayment

Revision ID: f9bc004c0670
Revises: 13d96edb4974
Create Date: 2025-12-30 16:53:10.165383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f9bc004c0670'
down_revision: Union[str, Sequence[str], None] = '13d96edb4974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- BLOQUE 1: LIMPIEZA Y RESTAURACIÓN DE ESTADO (CRÍTICO) ---
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    
    # 1. Borrar usuarios antiguos (Incompatibles)
    op.execute("DELETE FROM user") 
    
    # 2. Borrar tablas nuevas si existen
    op.execute("DROP TABLE IF EXISTS rolepermission")
    op.execute("DROP TABLE IF EXISTS salepayment")
    op.execute("DROP TABLE IF EXISTS permission")
    op.execute("DROP TABLE IF EXISTS role")
    
    # 3. Limpiar columna role_id en user
    try:
        op.execute("ALTER TABLE user DROP COLUMN role_id")
    except Exception:
        pass

    # 4. RESETEAR TABLA SALE (Para evitar errores de duplicado/faltante)
    # A. Borrar 'status' si ya se creó
    try:
        op.execute("ALTER TABLE sale DROP COLUMN status")
    except Exception:
        pass

    # B. Re-crear columnas viejas si se borraron (como dummies) para que el script pueda borrarlas
    try:
        op.execute("ALTER TABLE sale ADD COLUMN is_deleted TINYINT DEFAULT 0")
    except Exception:
        pass
    try:
        op.execute("ALTER TABLE sale ADD COLUMN payment_details JSON")
    except Exception:
        pass
    try:
        op.execute("ALTER TABLE sale ADD COLUMN payment_method VARCHAR(255)")
    except Exception:
        pass
        
    op.execute("SET FOREIGN_KEY_CHECKS=1")
    # -------------------------------------------------------------

    # --- BLOQUE 2: NORMALIZACIÓN DE DATOS ---
    op.execute("UPDATE fieldprice SET sport = 'futbol' WHERE sport LIKE 'Futbol%' OR sport LIKE 'fútbo%'")
    op.execute("UPDATE fieldprice SET sport = 'voley' WHERE sport LIKE 'Voley%'")
    op.execute("UPDATE fieldreservation SET sport = 'futbol' WHERE sport LIKE 'Futbol%' OR sport LIKE 'fútbo%'")
    op.execute("UPDATE fieldreservation SET sport = 'voley' WHERE sport LIKE 'Voley%'")

    op.execute("UPDATE fieldreservation SET status = 'pending' WHERE status = 'pendiente'")
    op.execute("UPDATE fieldreservation SET status = 'paid' WHERE status = 'pagado'")
    op.execute("UPDATE fieldreservation SET status = 'cancelled' WHERE status IN ('cancelado', 'eliminado')")
    # ----------------------------------------

    """Upgrade schema."""
    # ### commands auto generated by Alembic...
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_codename'), 'permission', ['codename'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('rolepermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('method_type', sa.Enum('cash', 'card', 'transfer', 'wallet', 'mixed', 'other', name='paymentmethodtype'), nullable=False),
    sa.Column('reference_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('fieldprice', 'sport',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Enum('futbol', 'voley', name='sporttype'),
               existing_nullable=False)
    op.alter_column('fieldreservation', 'sport',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Enum('futbol', 'voley', name='sporttype'),
               existing_nullable=False)
    op.alter_column('fieldreservation', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Enum('pending', 'paid', 'cancelled', 'refunded', name='reservationstatus'),
               existing_nullable=False)
    op.alter_column('paymentmethod', 'kind',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Enum('cash', 'card', 'transfer', 'wallet', 'mixed', 'other', name='paymentmethodtype'),
               existing_nullable=False)
    op.add_column('sale', sa.Column('status', sa.Enum('completed', 'cancelled', 'pending', name='salestatus'), nullable=False))
    op.drop_column('sale', 'is_deleted')
    op.drop_column('sale', 'payment_details')
    op.drop_column('sale', 'payment_method')
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'role')
    op.drop_column('user', 'privileges')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('privileges', mysql.JSON(), nullable=True))
    op.add_column('user', sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.add_column('sale', sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=False))
    op.add_column('sale', sa.Column('payment_details', mysql.JSON(), nullable=True))
    op.add_column('sale', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('sale', 'status')
    op.alter_column('paymentmethod', 'kind',
               existing_type=sa.Enum('cash', 'card', 'transfer', 'wallet', 'mixed', 'other', name='paymentmethodtype'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)
    op.alter_column('fieldreservation', 'status',
               existing_type=sa.Enum('pending', 'paid', 'cancelled', 'refunded', name='reservationstatus'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)
    op.alter_column('fieldreservation', 'sport',
               existing_type=sa.Enum('futbol', 'voley', name='sporttype'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)
    op.alter_column('fieldprice', 'sport',
               existing_type=sa.Enum('futbol', 'voley', name='sporttype'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)
    op.drop_table('salepayment')
    op.drop_table('rolepermission')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_codename'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###